"""add wallet model

Revision ID: 9c6a97619671
Revises: 203507278683
Create Date: 2022-11-10 10:26:57.095809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6a97619671'
down_revision = '203507278683'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='walletstatus'), nullable=True),
    sa.Column('owned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owned_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_access',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('wallet_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_access')
    op.drop_table('wallet')
    # ### end Alembic commands ###
